### ISSUE TITLE
make it possible to run pre and post commands

### ISSUE THREAD

**Issue by marten-seemann** [marten-seemann/multiple-go-modules#7]
Running the same command in every directory is a bit limiting. For example, when creating git commits, what we actually want to do is collect files from all directories (`git add`), and then just `git commit` once.
This happened here for example: https://github.com/ipfs/go-datastore/pull/179.

Proposed API:
```yml
steps:
  - name: Code Quality Checks
    uses: protocol/multiple-go-modules@master
    with:
      working-directory: scripts
      pre: echo "I'm only run once, in the parent directory"
      run: touch file && git add file
      post: git commit -m "add a file per directory"
```

@mvdan, what do you think?
